spring:
  datasource:
    url: "jdbc:postgresql://postgresql:5432/productdb"
    username: productdb
    password: productdb
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: validate

  flyway:
    locations: classpath:db/migration/postgres